admin/urls.py
from django.urls import path
from django.utils.decorators import decorator_from_middleware

from trivia.views import AdminTrivia, cancel_question, AdminTriviaResult
from .middleware import AdminCheckMiddleware
from .views import (dashboard, TeamsView, delete_team_view, EventsView, delete_event_view, games_view,
                    games_creation_view, game_matches_view, redirect_after_match_update, ImagesView, add_slider_image,
                    remove_slider_image, UsersView, delete_slider_image, game_edit_view, GamesSetting, user_games_view,
                    user_bet_slip, change_user_status, support_view, SupportResponse, SendMessage, game_delete_view,
                    CreditUserAccount, QualifiedPlayers)

admin_auth_decorator = decorator_from_middleware(AdminCheckMiddleware)
app_name = 'myadmin'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('teams', admin_auth_decorator(TeamsView.as_view()), name='teams'),
    path('teams/delete/<int:pk>', admin_auth_decorator(delete_team_view), name='delete_team'),
    path('events', admin_auth_decorator(EventsView.as_view()), name='events'),
    path('events/delete/<int:pk>', admin_auth_decorator(delete_event_view), name='delete_event'),
    path('games', admin_auth_decorator(games_view), name='games'),
    path('games/setting', admin_auth_decorator(GamesSetting.as_view()), name='games_setting'),
    path('trivia', admin_auth_decorator(AdminTrivia.as_view()), name='trivia'),
    path('trivia/result/<int:pk>', admin_auth_decorator(AdminTriviaResult.as_view()), name='trivia_result'),
    path('trivia/cancel/<int:pk>', admin_auth_decorator(cancel_question), name='trivia_cancel'),
    path('games/create', admin_auth_decorator(games_creation_view), name='games_create'),
    path('games/matches/<int:pk>', admin_auth_decorator(game_matches_view), name='game_matches'),
    path('games/edit/<int:pk>', admin_auth_decorator(game_edit_view), name='edit_game'),
    path('games/delete/<int:pk>', admin_auth_decorator(game_delete_view), name='delete_game'),
    path('games/matches/update/success/<int:pk>', admin_auth_decorator(redirect_after_match_update)),
    path('images', admin_auth_decorator(ImagesView.as_view()), name='images'),
    path('images/add/<int:pk>', admin_auth_decorator(add_slider_image), name='add_slider'),
    path('images/remove/<int:pk>', admin_auth_decorator(remove_slider_image), name='remove_slider'),
    path('images/delete/<int:pk>', admin_auth_decorator(delete_slider_image), name='delete_image'),
    path('users', admin_auth_decorator(UsersView.as_view()), name='users'),
    path('user/<int:pk>/games', admin_auth_decorator(user_games_view), name='user_games'),
    path('slip/<int:pk>', admin_auth_decorator(user_bet_slip), name='bet_slip'),
    path('status/change/<int:pk>', admin_auth_decorator(change_user_status), name='status_change'),
    path('support', admin_auth_decorator(support_view), name='support'),
    path('support/respond', admin_auth_decorator(SupportResponse.as_view()), name='support_response'),
    path('messages', admin_auth_decorator(SendMessage.as_view()), name='message'),
    path('users/credit-account', admin_auth_decorator(CreditUserAccount.as_view()), name='credit_user_account'),
    path('qualified-players', admin_auth_decorator(QualifiedPlayers.as_view()), name='qualified_players'),
]

core/urls.py
from django.urls import path
from .views import SliderView, AdminSliderView

urlpatterns = [
    path('user-slider', SliderView.as_view(), name='user_slider_view'),
    path('admin-slider', AdminSliderView.as_view(), name='admin_slider_view'),
]

templates/site_admin/images/index.html
{% extends "site_admin/layouts/base.html" %}
{% load static %}
{% block page_title %}Admin - Images{% endblock %}
{% load humanize %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="material-icons">close</i>
                            </button>
                            <span>
                                {{ message }}
                            </span>
                        </div>
                    {% endfor %}
                {% endif %}

                {% if form.errors %}
                    {% if form.errors.image %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="material-icons">close</i>
                            </button>
                            <span>Please select image to upload</span>
                        </div>
                    {% endif %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="material-icons">close</i>
                            </button>
                            <span>{{ error|escape }}</span>
                        </div>
                    {% endfor %}
                {% endif %}

                <button type="submit" class="btn btn-primary pull-right" data-toggle="modal" data-target="#image-add">
                    Add Image
                </button>
                <div class="clearfix"></div>

                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Images</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>
                                    Image
                                </th>
                                <th>
                                    Is Slider
                                </th>
                                <th>
                                    Actions
                                </th>
                                </thead>
                                <tbody>
                                {% for image in images %}
                                    <tr>
                                        <td><img src="{% get_media_prefix %}{{ image.image }}" class="img-circle"
                                                 style="height: 40px"></td>
                                        <td>{% if image.should_show %} YES {% else %} NO {% endif %}</td>
                                        <td>{% if image.should_show %}
                                            <a href="#" class="btn btn-danger"
                                               onclick="
                                                       event.preventDefault();
                                                       document.getElementById('remove-slider-form-{{ image.id }}').submit();"
                                            >
                                                Remove from slider
                                            </a>
                                            <form action="{% url 'myadmin:remove_slider' image.id %}" method="POST"
                                                  style="display: none;" id="remove-slider-form-{{ image.id }}">
                                                {% csrf_token %}
                                            </form>
                                        {% else %}
                                            <a href="#" class="btn btn-primary"
                                               onclick="
                                                       event.preventDefault();
                                                       document.getElementById('add-slider-form-{{ image.id }}').submit();"
                                            >
                                                Add to slider
                                            </a>
                                            <form action="{% url 'myadmin:add_slider' image.id %}" method="POST"
                                                  style="display: none;" id="add-slider-form-{{ image.id }}">
                                                {% csrf_token %}
                                            </form>
                                        {% endif %}
                                            <button type="button" class="btn btn-primary copy-data"
                                                    data-clipboard-text="{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ request.get_absolute_url }}{% get_media_prefix %}{{ image.image }}">
                                                Copy Link
                                            </button>
                                        <a href="#" style="color: black"
                                                onclick="
                                                        var result = confirm('Are you sure you want to delete this Image?');
                                                        if (result){

                                                        event.preventDefault();
                                                        document.getElementById('delete-form-{{image.id}}').submit();

                                                        }"
                                        >
                                            <i class="fa fa-trash cursor" ></i>
                                        </a>
                                            <form action="{% url 'myadmin:delete_image' image.id %}" method="POST"
                                                  style="display: none;" id="delete-form-{{image.id}}">
                                                {% csrf_token %}
                                            </form>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="100%" class="text-center">No Slider added</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block outer %}
    <div class="modal fade" id="image-add" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLongTitle">ADD IMAGE</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="btn btn-primary btn-file">
                                Click to Select Image
                                <input type="file" name="image">
                            </label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">ADD IMAGE</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}