admin/urls.py
from django.urls import path
from django.utils.decorators import decorator_from_middleware

from trivia.views import AdminTrivia, cancel_question, AdminTriviaResult
from .middleware import AdminCheckMiddleware
from .views import (dashboard, TeamsView, delete_team_view, EventsView, delete_event_view, games_view,
                    games_creation_view, game_matches_view, redirect_after_match_update, ImagesView, add_slider_image,
                    remove_slider_image, UsersView, delete_slider_image, game_edit_view, GamesSetting, user_games_view,
                    user_bet_slip, change_user_status, support_view, SupportResponse, SendMessage, game_delete_view,
                    CreditUserAccount, QualifiedPlayers)

admin_auth_decorator = decorator_from_middleware(AdminCheckMiddleware)
app_name = 'myadmin'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('teams', admin_auth_decorator(TeamsView.as_view()), name='teams'),
    path('teams/delete/<int:pk>', admin_auth_decorator(delete_team_view), name='delete_team'),
    path('events', admin_auth_decorator(EventsView.as_view()), name='events'),
    path('events/delete/<int:pk>', admin_auth_decorator(delete_event_view), name='delete_event'),
    path('games', admin_auth_decorator(games_view), name='games'),
    path('games/setting', admin_auth_decorator(GamesSetting.as_view()), name='games_setting'),
    path('trivia', admin_auth_decorator(AdminTrivia.as_view()), name='trivia'),
    path('trivia/result/<int:pk>', admin_auth_decorator(AdminTriviaResult.as_view()), name='trivia_result'),
    path('trivia/cancel/<int:pk>', admin_auth_decorator(cancel_question), name='trivia_cancel'),
    path('games/create', admin_auth_decorator(games_creation_view), name='games_create'),
    path('games/matches/<int:pk>', admin_auth_decorator(game_matches_view), name='game_matches'),
    path('games/edit/<int:pk>', admin_auth_decorator(game_edit_view), name='edit_game'),
    path('games/delete/<int:pk>', admin_auth_decorator(game_delete_view), name='delete_game'),
    path('games/matches/update/success/<int:pk>', admin_auth_decorator(redirect_after_match_update)),
    path('images', admin_auth_decorator(ImagesView.as_view()), name='images'),
    path('images/add/<int:pk>', admin_auth_decorator(add_slider_image), name='add_slider'),
    path('images/remove/<int:pk>', admin_auth_decorator(remove_slider_image), name='remove_slider'),
    path('images/delete/<int:pk>', admin_auth_decorator(delete_slider_image), name='delete_image'),
    path('users', admin_auth_decorator(UsersView.as_view()), name='users'),
    path('user/<int:pk>/games', admin_auth_decorator(user_games_view), name='user_games'),
    path('slip/<int:pk>', admin_auth_decorator(user_bet_slip), name='bet_slip'),
    path('status/change/<int:pk>', admin_auth_decorator(change_user_status), name='status_change'),
    path('support', admin_auth_decorator(support_view), name='support'),
    path('support/respond', admin_auth_decorator(SupportResponse.as_view()), name='support_response'),
    path('messages', admin_auth_decorator(SendMessage.as_view()), name='message'),
    path('users/credit-account', admin_auth_decorator(CreditUserAccount.as_view()), name='credit_user_account'),
    path('qualified-players', admin_auth_decorator(QualifiedPlayers.as_view()), name='qualified_players'),
]

core/urls.py
from django.urls import path
from .views import SliderView, AdminSliderView

urlpatterns = [
    path('user-slider', SliderView.as_view(), name='user_slider_view'),
    path('admin-slider', AdminSliderView.as_view(), name='admin_slider_view'),
]

templates/site_admin/layouts/base.html
{% load staticfiles %}
{% load site_utils %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    {% comment %}
    <link rel="apple-touch-icon" sizes="76x76" href="img/apple-icon.png"> {% endcomment %}
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        {% block page_title %}Admin{% endblock %}
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport' />
    <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    <link href="{% static 'admin/css/material-dashboard.css' %}" rel="stylesheet" />
{% block latter_css %} {% endblock %}
</head>

<body class="">
    <div class="wrapper" id="app">
        {% include "site_admin/layouts/sidebar.html" %}
        <div class="main-panel">
            {% include "site_admin/layouts/header.html" %}
            <div class="content">
                {% block content %}{% endblock %}
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright float-right">
                        &copy; {% now "Y" %}, all rights reserved
                    </div>
                </div>
            </footer>
        </div>

        {% block outer %} {% endblock %}
    </div>

    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'admin/js/core/bootstrap-material-design.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/moment.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/sweetalert2.js' %}"></script>
    <script src="{% static 'admin/js/plugins/jquery.validate.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/jquery.bootstrap-wizard.js' %}"></script>
    <script src="{% static 'admin/js/plugins/bootstrap-selectpicker.js' %}"></script>
    <script src="{% static 'admin/js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/bootstrap-tagsinput.js' %}"></script>
    <script src="{% static 'admin/js/plugins/jasny-bootstrap.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/fullcalendar.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/jquery-jvectormap.js' %}"></script>
    <script src="{% static 'admin/js/plugins/nouislider.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
    <script src="{% static 'admin/js/plugins/arrive.min.js' %}"></script>
    <script src="{% static 'admin/js/plugins/bootstrap-notify.js' %}"></script>
    <script src="{% static 'admin/js/plugins/clipboard.min.js' %}"></script>
    <script src="{% static 'admin/js/material-dashboard.js' %}" type="text/javascript"></script>
{% block latter_js %} {% endblock %}
</body>

</html>

templates/site_admin/layouts/header.html
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
    </div>
</nav>

templates/site_admin/layouts/sidebar.html
{% load staticfiles %}
{% load site_utils %}
<div class="sidebar" data-color="azure" data-background-color="white"
     data-image="{% static 'admin/img/sidebar-1.jpg' %}">
    <div class="logo">
        <a href="{% url 'myadmin:dashboard' %}" class="simple-text logo-normal">
            {% site_name %}
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item {% if request.path == '/admin/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:dashboard' %}">
                    <i class="material-icons">dashboard</i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="nav-item {% if request.path == '/admin/users' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:users' %}">
                    <i class="fa fa-users"></i>
                    <p>Users</p>
                </a>
            </li>
            <li class="nav-item {% if request.path == '/admin/teams' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:teams' %}">
                    <i class="fa fa-flag-checkered"></i>
                    <p>Teams</p>
                </a>
            </li>
            <li class="nav-item {% if request.path == '/admin/events' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:events' %}">
                    <i class="fa fa-trophy"></i>
                    <p>Events</p>
                </a>
            </li>
            <li class="nav-item {% if request.path == '/admin/games' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:games' %}">
                    <i class="material-icons">games</i>
                    <p>Games</p>
                </a>
            </li>
            <li class="nav-item {% if request.path == '/admin/games/setting' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:games_setting' %}">
                    <i class="material-icons">settings</i>
                    <p>Games Setting</p>
                </a>
            </li>
            <li class="nav-item {% if request.path == '/admin/images' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:images' %}">
                    <i class="material-icons">photo</i>
                    <p>Images</p>
                </a>
            </li>
            <li class="nav-item  {% if request.path == '/admin/support' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:support' %}">
                    <i class="material-icons">message</i>
                    <p>Support</p>
                </a>
            </li>
            <li class="nav-item  {% if request.path == '/admin/messages' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:message' %}">
                    <i class="material-icons">message</i>
                    <p>Bulk Messaging</p>
                </a>
            </li>
            <li class="nav-item  {% if request.path == '/admin/qualified-players' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:qualified_players' %}">
                    <i class="fa fa-trophy"></i>
                    <p>Qualified Winners</p>
                </a>
            </li>
            <li class="nav-item  {% if request.path == '/admin/trivia' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myadmin:trivia' %}">
                    <i class="fa fa-trophy"></i>
                    <p>Trivia</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'logoutPage' %}">
                    <i class="material-icons">exit_to_app</i>
                    <p>Logout</p>
                </a>
            </li>
        </ul>
    </div>
</div>